export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCES = "REGISTER_USER_SUCCES";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCES = "LOGIN_USER_SUCCES";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";

export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_PATIENT_BEGIN = "CREATE_PATIENT_BEGIN";
export const CREATE_PATIENT_SUCCES = "CREATE_PATIENT_SUCCES";
export const CREATE_PATIENT_ERROR = "CREATE_PATIENT_ERROR";

export const GET_PATIENTS_BEGIN = "GET_PATIENTS_BEGIN";
export const GET_PATIENTS_SUCCESS = "GET_PATIENTS_SUCCESS";

export const SET_EDIT_PATIENT = "SET_EDIT_PATIENT";

export const DELETE_PATIENT_BEGIN = "DELETE_PATIENT_BEGIN";

export const EDIT_PATIENT_BEGIN = "EDIT_PATIENT_BEGIN";
export const EDIT_PATIENT_SUCCES = "EDIT_PATIENT_SUCCES";
export const EDIT_PATIENT_ERROR = "EDIT_PATIENT_ERROR";

export const VIEW_PARAMS_PATIENT = "VIEW_PARAMS_PATIENT";

export const GET_ALLSTATS_SUCCESS = "GET_ALLSTATS_SUCCESS";

export const CLEAR_APPOINTMENT_VALUES = "CLEAR_APPOINTMENT_VALUES";
export const DISPLAY_ALERT_APPOINTMENT = "DISPLAY_ALERT_APPOINTMENT";
export const SEND_TO_APPOINTMENT = "SEND_TO_APPOINTMENT";

export const ADD_APPOINTMENT_SUCCES = "ADD_APPOINTMENT_SUCCES";

export const GET_APPOINTMENTS_SUCCESS = "GET_APPOINTMENTS_SUCCESS";

export const GET_NOT_APPROVMENT_USER_SUCCES = "GET_NOT_APPROVMENT_USER_SUCCES";

export const UPDATE_APPROVMENT = "UPDATE_APPROVMENT";
export const UPDATE_APPROVMENT_FALSE = "UPDATE_APPROVMENT_FALSE";

export const UPDATE_PARAMS_VITAUX = "UPDATE_PARAMS_VITAUX";

export const FILE_PARAMS_VITAUX = "FILE_PARAMS_VITAUX";

export const GET_APPOINTMENTS_PATINETID_SUCCESS =
  "GET_APPOINTMENTS_PATINETID_SUCCESS";

export const GET_APPONTMENT_UPDATE = "GET_APPONTMENT_UPDATE";

export const EDIT_APPOINTMENT_SUCCES = "EDIT_APPOINTMENT_SUCCES";

export const GET_APPOINTMENT_SUCCESS = "GET_APPOINTMENT_SUCCESS";

export const CLEAR_VALUES_APPOINTMENT = "CLEAR_VALUES_APPOINTMENT";

export const NOTIFICATIONS_SUCCES = "NOTIFICATIONS_SUCCES";

export const NOTIFICATIONS_BEGIN = "NOTIFICATIONS_BEGIN";

export const DELETE_NOTIFICATIONS_BEGIN = "DELETE_NOTIFICATIONS_BEGIN";

export const DELETE_NOTIFICATIONS_SUCCES = "DELETE_NOTIFICATIONS_SUCCES";
